### ISSUE TITLE
Date localisation does not work in Windows

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#112]
Dates are currently being localised in metanorma-nist using the twitter_cldr gem.

The latest checkin breaks Appveyor: 

````
Failure/Error: DateTime.parse(isodate).localize(:en).to_additional_s("yMMMM")
628
629     TZInfo::DataSourceNotFound:
630       No source of timezone data could be found.
631       Please refer to https://tzinfo.github.io/datasourcenotfound for help resolving this error.
632     # ./lib/isodoc/nist/metadata.rb:154:in `monthyr'
633     # ./lib/isodoc/nist/metadata.rb:114:in `version'
634     # ./lib/isodoc/nist/base_convert.rb:233:in `info'
635     # ./spec/isodoc/nist/html_convert_spec.rb:373:in `block (2 levels) in <top (required)>'
636     # ------------------
637     # --- Caused by: ---
638     # TZInfo::DataSources::ZoneinfoDirectoryNotFound:
639     #   None of the paths included in TZInfo::DataSources::ZoneinfoDataSource.search_path are valid zoneinfo directories.
````

I am quite happy to abandon twitter_cldr and use Date.strftime; I've already had to for some of the date formatting. But before I do, Alex, could you check whether there is some easy fix?

**Comment by CAMOBAP795** [comment]
@opoudjis on it

**Comment by opoudjis** [comment]
... Closing this ticket then.
