### ISSUE TITLE
Unable to generate PDF output in NIST.SP.800-90B

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-nist#183]
For some reason, I can't generate a PDF output for **NIST.SP.800-90B** (located in: https://gitlab.com/metanorma/mn-samples-nist/)

Error log:
````
$ bundle exec metanorma -t nist -x pdf sources/NIST.SP.800-90B.adoc
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from C:/tools/ruby25/lib/ruby/gems/2.5.0/specifications/sterile-1.0.14.gemspec:15.
BZ2 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
BZ2 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Cac97 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Cac97 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
CoNa98 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
CoNa98 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Fel50 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Fel50 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS140 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS140 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS180 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS180 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS197 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS197 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS198 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS198 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS202 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
FIPS202 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
HaFis15 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
HaFis15 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
HD12 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
HD12 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
IG140-2 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
IG140-2 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Kel15 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Kel15 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Mau92 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Mau92 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
RaSt98 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
RaSt98 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Sal07 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Sal07 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Shan51 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
Shan51 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-38B does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-38B does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-57 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-57 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-90A does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-90A does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-90C does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-90C does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-107 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
SP800-107 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
MathML 500 of 1533
MathML 1000 of 1533
MathML 1500 of 1533
Style Warning: (XML Line 000180): Hanging paragraph in clause
Style Warning: (XML Line 000394): Hanging paragraph in clause
Style Warning: (XML Line 000440): Hanging paragraph in clause
Style Warning: (XML Line 000497): Hanging paragraph in clause
Style Warning: (XML Line 000631): Hanging paragraph in clause
Style Warning: (XML Line 000660): Hanging paragraph in clause
Style Warning: (XML Line 000769): Hanging paragraph in clause
Style Warning: (XML Line 000902): Hanging paragraph in clause
Style Warning: (XML Line 000937): Hanging paragraph in clause
Style Warning: (XML Line 001125): Hanging paragraph in clause
Style Warning: (XML Line 001344): Hanging paragraph in clause
Style Warning: (XML Line 001473): Hanging paragraph in clause
Style Warning: (XML Line 001720): Hanging paragraph in clause
Style Warning: (XML Line 001723): Hanging paragraph in clause
Style Warning: (XML Line 002049): Hanging paragraph in clause
Style Warning: (XML Line 002425): Hanging paragraph in clause
Style Warning: (XML Line 002509): Hanging paragraph in clause
Style Warning: (XML Line 005239): Hanging paragraph in clause
Style Warning: (XML Line 005244): Hanging paragraph in clause
Style Warning: (XML Line 002103): Table should have title
Style Warning: (XML Line 002158): Table should have title
Style Warning: (XML Line 002650): Table should have title
Style Warning: (XML Line 002689): Table should have title
Style Warning: (XML Line 002790): Table should have title
Style Warning: (XML Line 002826): Table should have title
Style Warning: (XML Line 003030): Table should have title
Style Warning: (XML Line 003297): Table should have title
Style Warning: (XML Line 003511): Table should have title
Style Warning: (XML Line 003753): Table should have title
Style Warning: (XML Line 003891): Table should have title
Style Warning: (XML Line 004087): Table should have title
Syntax: (XML Line 000005:64): value of attribute "type" is invalid; must be equal to "alternative", "main", "original", "subtitle" or "unofficial"
Syntax: (XML Line 000225:76): element "acknowledgements" not allowed here; expected the element end-tag or element "clause", "executivesummary" or "reviewernote"
Syntax: (XML Line 000225:76): found attribute "id", but no attributes allowed here
Syntax: (XML Line 000225:76): found attribute "obligation", but no attributes allowed here
Syntax: (XML Line 000226:47): found attribute "id", but no attributes allowed here
Syntax: (XML Line 000298:64): found attribute "type", but no attributes allowed here
Syntax: (XML Line 001542:62): element "ol" not allowed here; expected the element end-tag or element "audio", "dl", "figure", "fn", "image", "name", "note", "p", "pre", "source" or "video"
Syntax: (XML Line 001621:62): element "ol" not allowed here; expected the element end-tag or element "audio", "dl", "figure", "fn", "image", "name", "note", "p", "pre", "source" or "video"
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/output/pdf.rb:18:in `convert': Navigation Timeout Exceeded: 30000ms exceeded (RuntimeError)
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at C:\Users\Manuel\AppData\Roaming\npm\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Manuel\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (C:\Users\Manuel\AppData\Roaming\npm\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (C:\Users\Manuel\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:112:23)
    at createPdf (C:\tools\ruby25\lib\ruby\gems\2.5.0\gems\metanorma-1.0.0\bin\metanorma-pdf.js:16:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.22/lib/isodoc/pdf_convert.rb:33:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-nist-1.0.3/lib/metanorma/nist/processor.rb:36:in `output'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:203:in `block in process_extensions'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:194:in `each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:194:in `process_extensions'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:20:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:41:in `compile_file'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:29:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:33:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/command.rb:35:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli.rb:60:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/exe/metanorma:20:in `<top (required)>'
        from C:/tools/ruby25/bin/metanorma:23:in `load'
        from C:/tools/ruby25/bin/metanorma:23:in `<main>'

````

HTML and doc outputs are doing fine.

Thanks!

**Comment by ronaldtse** [comment]
This ticket is tracked here: https://github.com/metanorma/metanorma/issues/99

Problem is number of formulas causing Puppeteer/Chrome to take excessive time in rendering.

**Comment by opoudjis** [comment]
I am surprised, since this did used to generated within the 30 sec threshold...

**Comment by ronaldtse** [comment]
I had the same issue, no idea why.

**Comment by CAMOBAP** [comment]
A timeout was increased in the scope of https://github.com/metanorma/metanorma/issues/99

**Comment by ronaldtse** [comment]
I think metanorma-nist now uses mn2pdf PDF output so puppeteer timeouts should no longer be relevant.
