### ISSUE TITLE
Failure with AsciiMath formula in SP 800-90B

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#215]
There is an error raised in compilation of documents due to the new AsciiMath 2.0.0 release:

```
bundler: failed to load command: metanorma (/opt/hostedtoolcache/Ruby/2.6.6/x64/bin/metanorma)
1520
NoMethodError: undefined method `each' for #<AsciiMath::AST::Number:0x000055cc8328f1b8>
1521
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciimath-2.0.0/lib/asciimath/parser.rb:669:in `block in convert_to_matrix'
1522
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciimath-2.0.0/lib/asciimath/parser.rb:660:in `map'
1523
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciimath-2.0.0/lib/asciimath/parser.rb:660:in `convert_to_matrix'
1524
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciimath-2.0.0/lib/asciimath/parser.rb:600:in `parse_simple_expression'
1525
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciimath-2.0.0/lib/asciimath/parser.rb:545:in `parse_intermediate_expression'
1526
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciimath-2.0.0/lib/asciimath/parser.rb:519:in `parse_expression'
1527
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciimath-2.0.0/lib/asciimath/parser.rb:508:in `parse'
1528
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciimath-2.0.0/lib/asciimath/parser.rb:770:in `parse'
1529
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/html2doc-1.0.3/lib/html2doc/math.rb:12:in `asciimath_to_mathml1'
1530
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/html2doc-1.0.3/lib/html2doc/math.rb:22:in `block in asciimath_to_mathml'
1531
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/html2doc-1.0.3/lib/html2doc/math.rb:19:in `each'
1532
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/html2doc-1.0.3/lib/html2doc/math.rb:19:in `each_slice'
1533
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/html2doc-1.0.3/lib/html2doc/math.rb:19:in `each'
1534
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/html2doc-1.0.3/lib/html2doc/math.rb:19:in `map'
1535
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/html2doc-1.0.3/lib/html2doc/math.rb:19:in `with_index'
1536
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/html2doc-1.0.3/lib/html2doc/math.rb:19:in `asciimath_to_mathml'
1537
```

This is the formula that caused the break:

```
--------------------
P(X >= X_( max )) = sum_(j = X_( max ))^(1000) ((1000), (j)) p^j (1 - p)^(1000 - j)
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
#<AsciiMath::Tokenizer:0x00007fb069c47d10>
(1000)
(j)
(1000)
1000
```

**Comment by opoudjis** [comment]
That formula is not breaking latest standoc; could you please confirm whether this bug is still live?

**Comment by opoudjis** [comment]
... This was fixed in https://github.com/asciidoctor/asciimath/issues/48 : closing
