### ISSUE TITLE
Potential issue with SASSC refactor in NIST CSWP

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#224]
https://github.com/metanorma/metanorma-nist/blob/b716d1b867a95ccb7cc9133e8294392f261dcf9f/lib/isodoc/nist/word_convert.rb#L24

This line indicates that NIST CSWP still relies on a `scss` file for rendering, is this a missed change of the sassc refactor?

Ping @w00lf @opoudjis

**Comment by CAMOBAP** [comment]
@w00lf @opoudjis can you confirm that this issue related to:

```
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/convert.rb:167:in `require': cannot load such file -- sassc (LoadError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/convert.rb:167:in `convert_scss'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/convert.rb:187:in `generate_css'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/convert.rb:108:in `populate_css'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/convert.rb:202:in `block (2 levels) in convert1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/convert.rb:199:in `block in convert1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/function/utils.rb:31:in `noko'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/convert.rb:198:in `convert1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.1.3/lib/isodoc/nist/word_convert.rb:30:in `convert1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/convert.rb:237:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.3/lib/isodoc/word_convert.rb:40:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.1.3/lib/metanorma/nist/processor.rb:37:in `output'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:245:in `block in process_extensions'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:234:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:234:in `process_extensions'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:24:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.3.3.1/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.3.3.1/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.3.3.1/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.3.3.1/lib/metanorma/cli/command.rb:37:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.3.3.1/lib/metanorma/cli.rb:61:in `start'
	from /__enclose_io_memfs__/local/metanorma:186:in `<main>'
```
?

**Comment by w00lf** [comment]
> https://github.com/metanorma/metanorma-nist/blob/b716d1b867a95ccb7cc9133e8294392f261dcf9f/lib/isodoc/nist/word_convert.rb#L24
> 
> This line indicates that NIST CSWP still relies on a `scss` file for rendering, is this a missed change of the sassc refactor?
> 
> Ping @w00lf @opoudjis

Added hotfix to isodoc that address this particular and any other issues that can occur with custom options manioulation.

**Comment by opoudjis** [comment]
Note, @ronaldtse, that with @w00lf's refactor, flavours continue to name stylesheets consistently as scss. The conversion to css is handled within in isodoc, and if a precompiled version is available (suffixed as css), that is used instead.
